-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;
create user 'sekuid' identified by 'sekupw';
grant all privileges on mydb.* to 'sekuid';
-- -----------------------------------------------------
-- Table `mydb`.`Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Answer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Answer` (
  `id` INT NOT NULL,
  `number` VARCHAR(45) NULL,
  `name` VARCHAR(50) NULL,
  `answer` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pw` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`board_free`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`board_free` ;

CREATE TABLE IF NOT EXISTS `mydb`.`board_free` (
  `b_no` INT NOT NULL AUTO_INCREMENT,
  `b_title` VARCHAR(500) NULL,
  `b_password` VARCHAR(45) NULL,
  `b_content` VARCHAR(1000) NULL,
  `b_date` VARCHAR(45) NULL,
  `b_hit` VARCHAR(45) NULL,
  `b_id` VARCHAR(45) NULL,
  `b_filename` VARCHAR(100) NULL,
  `b_protected` VARCHAR(45) NULL,
  `b_pwd` VARCHAR(45) NULL,
  `b_filepath` VARCHAR(100) NULL,
  PRIMARY KEY (`b_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`board_free2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`board_free2` ;

CREATE TABLE IF NOT EXISTS `mydb`.`board_free2` (
  `b_no` INT NOT NULL AUTO_INCREMENT,
  `b_title` VARCHAR(500) NULL,
  `b_password` VARCHAR(45) NULL,
  `b_content` VARCHAR(1000) NULL,
  `b_date` VARCHAR(45) NULL,
  `b_hit` VARCHAR(45) NULL,
  `b_id` VARCHAR(45) NULL,
  `b_filename` VARCHAR(100) NULL,
  `b_protected` VARCHAR(45) NULL,
  `b_pwd` VARCHAR(45) NULL,
  `b_filepath` VARCHAR(100) NULL,
  PRIMARY KEY (`b_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`listtohacker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`listtohacker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`listtohacker` (
  `id` INT NOT NULL,
  `no` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`member` ;

CREATE TABLE IF NOT EXISTS `mydb`.`member` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(45) NOT NULL,
  `pw` VARCHAR(50) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `birthday` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `hobby` VARCHAR(45) NOT NULL,
  `a_no` VARCHAR(45) NULL,
  PRIMARY KEY (`no`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
